import "./globals.css";
import MainHeader from "@/components/header/main-header/page";


export const metadata = {
  title: "Next Form",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainHeader />
        <div className="mx-30 my-10">
          {children}
        </div>

      </body>
    </html>
  );
}
